#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalaffairsSOP
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ESRVDB_RPT")]
	public partial class SOPDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttdsopdata(tdsopdata instance);
    partial void Updatetdsopdata(tdsopdata instance);
    partial void Deletetdsopdata(tdsopdata instance);
    partial void Inserttdsopdata_temp(tdsopdata_temp instance);
    partial void Updatetdsopdata_temp(tdsopdata_temp instance);
    partial void Deletetdsopdata_temp(tdsopdata_temp instance);
    partial void InserttccaseInstructiondata(tccaseInstructiondata instance);
    partial void UpdatetccaseInstructiondata(tccaseInstructiondata instance);
    partial void DeletetccaseInstructiondata(tccaseInstructiondata instance);
    #endregion
		
		public SOPDataDataContext() : 
				base(global::LegalaffairsSOP.Properties.Settings.Default.ESRVDB_RPTConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SOPDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SOPDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SOPDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SOPDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tdsopdata> tdsopdata
		{
			get
			{
				return this.GetTable<tdsopdata>();
			}
		}
		
		public System.Data.Linq.Table<tdsopdata_temp> tdsopdata_temp
		{
			get
			{
				return this.GetTable<tdsopdata_temp>();
			}
		}
		
		public System.Data.Linq.Table<tccaseInstructiondata> tccaseInstructiondata
		{
			get
			{
				return this.GetTable<tccaseInstructiondata>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tdsopdata")]
	public partial class tdsopdata : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _orgid;
		
		private string _sopno;
		
		private string _orgname;
		
		private string _sopname;
		
		private string _url;
		
		private string _status;
		
		private System.Nullable<System.DateTime> _upddate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnorgidChanging(string value);
    partial void OnorgidChanged();
    partial void OnsopnoChanging(string value);
    partial void OnsopnoChanged();
    partial void OnorgnameChanging(string value);
    partial void OnorgnameChanged();
    partial void OnsopnameChanging(string value);
    partial void OnsopnameChanged();
    partial void OnurlChanging(string value);
    partial void OnurlChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void OnupddateChanging(System.Nullable<System.DateTime> value);
    partial void OnupddateChanged();
    #endregion
		
		public tdsopdata()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orgid", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string orgid
		{
			get
			{
				return this._orgid;
			}
			set
			{
				if ((this._orgid != value))
				{
					this.OnorgidChanging(value);
					this.SendPropertyChanging();
					this._orgid = value;
					this.SendPropertyChanged("orgid");
					this.OnorgidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sopno", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string sopno
		{
			get
			{
				return this._sopno;
			}
			set
			{
				if ((this._sopno != value))
				{
					this.OnsopnoChanging(value);
					this.SendPropertyChanging();
					this._sopno = value;
					this.SendPropertyChanged("sopno");
					this.OnsopnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orgname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string orgname
		{
			get
			{
				return this._orgname;
			}
			set
			{
				if ((this._orgname != value))
				{
					this.OnorgnameChanging(value);
					this.SendPropertyChanging();
					this._orgname = value;
					this.SendPropertyChanged("orgname");
					this.OnorgnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sopname", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string sopname
		{
			get
			{
				return this._sopname;
			}
			set
			{
				if ((this._sopname != value))
				{
					this.OnsopnameChanging(value);
					this.SendPropertyChanging();
					this._sopname = value;
					this.SendPropertyChanged("sopname");
					this.OnsopnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_url", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string url
		{
			get
			{
				return this._url;
			}
			set
			{
				if ((this._url != value))
				{
					this.OnurlChanging(value);
					this.SendPropertyChanging();
					this._url = value;
					this.SendPropertyChanged("url");
					this.OnurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_upddate", DbType="DateTime")]
		public System.Nullable<System.DateTime> upddate
		{
			get
			{
				return this._upddate;
			}
			set
			{
				if ((this._upddate != value))
				{
					this.OnupddateChanging(value);
					this.SendPropertyChanging();
					this._upddate = value;
					this.SendPropertyChanged("upddate");
					this.OnupddateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tdsopdata_temp")]
	public partial class tdsopdata_temp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _orgid;
		
		private string _sopno;
		
		private string _orgname;
		
		private string _sopname;
		
		private string _url;
		
		private string _status;
		
		private System.Nullable<System.DateTime> _upddate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnorgidChanging(string value);
    partial void OnorgidChanged();
    partial void OnsopnoChanging(string value);
    partial void OnsopnoChanged();
    partial void OnorgnameChanging(string value);
    partial void OnorgnameChanged();
    partial void OnsopnameChanging(string value);
    partial void OnsopnameChanged();
    partial void OnurlChanging(string value);
    partial void OnurlChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void OnupddateChanging(System.Nullable<System.DateTime> value);
    partial void OnupddateChanged();
    #endregion
		
		public tdsopdata_temp()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orgid", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string orgid
		{
			get
			{
				return this._orgid;
			}
			set
			{
				if ((this._orgid != value))
				{
					this.OnorgidChanging(value);
					this.SendPropertyChanging();
					this._orgid = value;
					this.SendPropertyChanged("orgid");
					this.OnorgidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sopno", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string sopno
		{
			get
			{
				return this._sopno;
			}
			set
			{
				if ((this._sopno != value))
				{
					this.OnsopnoChanging(value);
					this.SendPropertyChanging();
					this._sopno = value;
					this.SendPropertyChanged("sopno");
					this.OnsopnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orgname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string orgname
		{
			get
			{
				return this._orgname;
			}
			set
			{
				if ((this._orgname != value))
				{
					this.OnorgnameChanging(value);
					this.SendPropertyChanging();
					this._orgname = value;
					this.SendPropertyChanged("orgname");
					this.OnorgnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sopname", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string sopname
		{
			get
			{
				return this._sopname;
			}
			set
			{
				if ((this._sopname != value))
				{
					this.OnsopnameChanging(value);
					this.SendPropertyChanging();
					this._sopname = value;
					this.SendPropertyChanged("sopname");
					this.OnsopnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_url", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string url
		{
			get
			{
				return this._url;
			}
			set
			{
				if ((this._url != value))
				{
					this.OnurlChanging(value);
					this.SendPropertyChanging();
					this._url = value;
					this.SendPropertyChanged("url");
					this.OnurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_upddate", DbType="DateTime")]
		public System.Nullable<System.DateTime> upddate
		{
			get
			{
				return this._upddate;
			}
			set
			{
				if ((this._upddate != value))
				{
					this.OnupddateChanging(value);
					this.SendPropertyChanging();
					this._upddate = value;
					this.SendPropertyChanged("upddate");
					this.OnupddateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tccaseInstructiondata")]
	public partial class tccaseInstructiondata : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _datano;
		
		private string _masterno;
		
		private string _tmcaseheaderno;
		
		private string _title;
		
		private string _description;
		
		private string _type;
		
		private string _atthvalue;
		
		private string _crtuser;
		
		private System.DateTime _crtdate;
		
		private string _upduser;
		
		private System.DateTime _upddate;
		
		private string _sopno;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OndatanoChanging(string value);
    partial void OndatanoChanged();
    partial void OnmasternoChanging(string value);
    partial void OnmasternoChanged();
    partial void OntmcaseheadernoChanging(string value);
    partial void OntmcaseheadernoChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void OnatthvalueChanging(string value);
    partial void OnatthvalueChanged();
    partial void OncrtuserChanging(string value);
    partial void OncrtuserChanged();
    partial void OncrtdateChanging(System.DateTime value);
    partial void OncrtdateChanged();
    partial void OnupduserChanging(string value);
    partial void OnupduserChanged();
    partial void OnupddateChanging(System.DateTime value);
    partial void OnupddateChanged();
    partial void OnsopnoChanging(string value);
    partial void OnsopnoChanged();
    #endregion
		
		public tccaseInstructiondata()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datano", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string datano
		{
			get
			{
				return this._datano;
			}
			set
			{
				if ((this._datano != value))
				{
					this.OndatanoChanging(value);
					this.SendPropertyChanging();
					this._datano = value;
					this.SendPropertyChanged("datano");
					this.OndatanoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masterno", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string masterno
		{
			get
			{
				return this._masterno;
			}
			set
			{
				if ((this._masterno != value))
				{
					this.OnmasternoChanging(value);
					this.SendPropertyChanging();
					this._masterno = value;
					this.SendPropertyChanged("masterno");
					this.OnmasternoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tmcaseheaderno", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string tmcaseheaderno
		{
			get
			{
				return this._tmcaseheaderno;
			}
			set
			{
				if ((this._tmcaseheaderno != value))
				{
					this.OntmcaseheadernoChanging(value);
					this.SendPropertyChanging();
					this._tmcaseheaderno = value;
					this.SendPropertyChanged("tmcaseheaderno");
					this.OntmcaseheadernoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="NVarChar(1) NOT NULL", CanBeNull=false)]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_atthvalue", DbType="NChar(200) NOT NULL", CanBeNull=false)]
		public string atthvalue
		{
			get
			{
				return this._atthvalue;
			}
			set
			{
				if ((this._atthvalue != value))
				{
					this.OnatthvalueChanging(value);
					this.SendPropertyChanging();
					this._atthvalue = value;
					this.SendPropertyChanged("atthvalue");
					this.OnatthvalueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_crtuser", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string crtuser
		{
			get
			{
				return this._crtuser;
			}
			set
			{
				if ((this._crtuser != value))
				{
					this.OncrtuserChanging(value);
					this.SendPropertyChanging();
					this._crtuser = value;
					this.SendPropertyChanged("crtuser");
					this.OncrtuserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_crtdate", DbType="DateTime NOT NULL")]
		public System.DateTime crtdate
		{
			get
			{
				return this._crtdate;
			}
			set
			{
				if ((this._crtdate != value))
				{
					this.OncrtdateChanging(value);
					this.SendPropertyChanging();
					this._crtdate = value;
					this.SendPropertyChanged("crtdate");
					this.OncrtdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_upduser", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string upduser
		{
			get
			{
				return this._upduser;
			}
			set
			{
				if ((this._upduser != value))
				{
					this.OnupduserChanging(value);
					this.SendPropertyChanging();
					this._upduser = value;
					this.SendPropertyChanged("upduser");
					this.OnupduserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_upddate", DbType="DateTime NOT NULL")]
		public System.DateTime upddate
		{
			get
			{
				return this._upddate;
			}
			set
			{
				if ((this._upddate != value))
				{
					this.OnupddateChanging(value);
					this.SendPropertyChanging();
					this._upddate = value;
					this.SendPropertyChanged("upddate");
					this.OnupddateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sopno", DbType="VarChar(10)")]
		public string sopno
		{
			get
			{
				return this._sopno;
			}
			set
			{
				if ((this._sopno != value))
				{
					this.OnsopnoChanging(value);
					this.SendPropertyChanging();
					this._sopno = value;
					this.SendPropertyChanged("sopno");
					this.OnsopnoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
